# Site settings
title: Adrien Chrétien
author: Adrien Chrétien
email: contact@achretien.fr
lang: fr
description: "Développeur et intégrateur web"
url: "http://achretien.fr"

# Build settings
markdown: kramdown
permalink: pretty
