# Site settings
title: Adrien Chrétien
author: Adrien Chrétien
email: contact@achretien.fr
lang: fr
description: "Développeur et intégrateur web"
url: "http://achretien.fr"

exclude: ["LICENSE", "README.md"]

defaults:
  - 
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"

# Build settings
markdown: kramdown
paginate: 10
permalink: pretty