# Site settings
title: Adrien Chrétien
author: Adrien Chrétien
email: contact@achretien.fr
lang: fr
description: "Notes et liens d'un développeur et intégrateur web"
url: "http://achretien.fr"

exclude: ["LICENSE", "README.md", CNAME]

defaults:
  - 
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"

# Build settings
markdown: kramdown
paginate: 10
permalink: pretty
excerpt_separator: "\r\n\r\n"