# Site settings
title: Adrien Chrétien
author: Adrien Chrétien
email: contact@achretien.fr
lang: fr
description: "Notes et liens d'un intégrateur web"
url: "http://achretien.fr"

exclude: [LICENSE, README.md, CNAME, Gemfile, Gemfile.lock]
footer_quotes:
  - "See you space cowboy…"
  - "Easy come, easy go…"
  - "To be continued."
  - "Do you have a comrade?"
  - "Life is but a dream…"
  - "See you space samurai…"
  - "Are you living in the real world?"
  - "You're gonna carry that weight."

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      menu-index: 3
  - scope:
      path: "blog"
    values:
      menu-index: 3

# Build settings
markdown: kramdown
paginate: 10
permalink: "/blog/:categories/:year/:month/:day/:title/"
excerpt_separator: "\r\n\r\n"
sass:
  style: :compressed
gems:
  - jekyll-redirect-from

# Collections
collections:
  patterns:
    output: true
