# Site settings
title: Adrien Chrétien
author: Adrien Chrétien
email: contact@achretien.fr
lang: fr
description: "Notes et liens d'un intégrateur web"
url: "http://achretien.fr"

exclude: [LICENSE, README.md, CNAME, Gemfile, Gemfile.lock]

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
collections:
- patterns

# Build settings
markdown: kramdown
paginate: 10
permalink: pretty
excerpt_separator: "\r\n\r\n"