# Site settings
title: Adrien Chrétien
author: Adrien Chrétien
email: contact@achretien.fr
lang: fr
description: "Notes et liens d'un intégrateur web"
url: "http://achretien.fr"

exclude: [LICENSE, README.md, CNAME, Gemfile, Gemfile.lock, fontsquirrel_config.txt, style-guide.html]
footer_quotes:
  -
    quote: "See you space cowboy…"
    lang: "en"
  -
    quote: "Easy come, easy go…"
    lang: "en"
  -
    quote: "Do you have a comrade?"
    lang: "en"
  -
    quote: "See you space samurai…"
    lang: "en"
  -
    quote: "Are you living in the real world?"
    lang: "en"
  -
    quote: "Si ça se pense, c'est que ça se tente !"
    lang: "fr"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      menu-index: 1
  -
    scope:
      path: "blog"
    values:
      menu-index: 1

# Build settings
markdown: kramdown
permalink: "/blog/:categories/:year/:month/:day/:title/"
excerpt_separator: "\r\n\r\n"
sass:
  style: :compressed
gems:
  - jekyll-redirect-from

# Collections
# collections:
#   patterns:
#     output: true
